- name: Import the public key used by the package management system
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: Import Mongodb Repo
  apt_repository:
    repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/4.0 multiverse
    filename: mongodb-org-{{mongodb_ver}}

- name: Install Mongodb 
  apt:
    name: mongodb-org
    update_cache: yes

- name: mongodb tmpfiles.d
  shell: |
    echo 'd /var/run/mongodb/ 0755 mongodb mongodb' > /etc/tmpfiles.d/mongodb.conf
    systemd-tmpfiles --create

- name: Create Databases Directory
  file:
    path: /data/mongo
    state: directory
    owner: mongodb
    group: mongodb